services:
  # Lock manager nodes (build from project root so source is included)
  lock-manager-1:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: lock_manager
      NODE_ID: lock1
      PORT: 8001
      REDIS_HOST: redis
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - redis

  lock-manager-2:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: lock_manager
      NODE_ID: lock2
      PORT: 8002
      REDIS_HOST: redis
    ports:
      - "8002:8002"
    restart: unless-stopped
    depends_on:
      - redis

  lock-manager-3:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: lock_manager
      NODE_ID: lock3
      PORT: 8003
      REDIS_HOST: redis
    ports:
      - "8003:8003"
    restart: unless-stopped
    depends_on:
      - redis

  # Queue nodes
  queue-node-1:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: queue
      NODE_ID: queue1
      PORT: 8011
      REDIS_HOST: redis
    ports:
      - "8011:8011"
    restart: unless-stopped
    depends_on:
      - redis

  queue-node-2:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: queue
      NODE_ID: queue2
      PORT: 8012
      REDIS_HOST: redis
    ports:
      - "8012:8012"
    restart: unless-stopped
    depends_on:
      - redis

  queue-node-3:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: queue
      NODE_ID: queue3
      PORT: 8013
      REDIS_HOST: redis
    ports:
      - "8013:8013"
    restart: unless-stopped
    depends_on:
      - redis

  # Cache nodes
  cache-node-1:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: cache
      NODE_ID: cache1
      PORT: 8021
      REDIS_HOST: redis
    ports:
      - "8021:8021"
    restart: unless-stopped
    depends_on:
      - redis

  cache-node-2:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: cache
      NODE_ID: cache2
      PORT: 8022
      REDIS_HOST: redis
    ports:
      - "8022:8022"
    restart: unless-stopped
    depends_on:
      - redis

  cache-node-3:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ../.env
    environment:
      NODE_TYPE: cache
      NODE_ID: cache3
      PORT: 8023
      REDIS_HOST: redis
    ports:
      - "8023:8023"
    restart: unless-stopped
    depends_on:
      - redis

  # Redis for shared state
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  default:
    driver: bridge